### ISSUE TITLE
Split code base to support both GitHub App and GitHub action.

### ISSUE THREAD

**Issue by jetersen** [release-drafter/release-drafter#549]
GitHub actions is referred to as actions.
GitHub app is referred to as app.

Would like to split the code base.
This would allow to improve actions and app separately.

There are certain flows that works for actions but not for the app.

- App is experience H12 on heroku, we would need to introduce something like [http delayed response](https://github.com/extrabacon/http-delayed-response)
- Actions ought to run without the use of a docker image. Yes probot adapter exists but it's a workaround in my opinion. 
- Actions is much more extensible take #546 for example.

I have a working prototype, still sorting out the test kinks.

**Comment by mikepenz** [comment]
@jetersen would there be a way to help testing a SNAPSHOT of the new github action? the compilation of the docker image adds quite a bit of overhead for every single build. 

Tried to find an approach to cache that bit, but was not able to find a proper solution so far.

**Comment by matfax** [comment]
@mikepenz This is indeed 40 to 50 seconds of delay that could be saved. The problem is that GitHub doesn't use docker caching, otherwise most of it would be skipped. That's why docker actions are only supposed to include entrypoints but other than that, rely on prebuilt images fetched from somewhere else.

If prebuilt docker images are used, the runtime wouldn't be much of a difference if you consider that GitHub also adds significant overhead to node actions (by library management/inclusion). Moreover, node actions are limited to version 12 at the moment. There's no dependency management possible, hence no way to track compatibility.

That's why I would recommend building docker images on release and pushing them to a docker repository (the official GitHub docker repository might turn out faster to access). Then, use a docker action to fetch the prebuilt image. The preparation time should decrease to 5 - 10 seconds and no restructuring is necessary.  You would still have to find a way so that the GitHub App doesn't run on every event, unlike the action (#632). This could be solved by an argument that is passed from the entrypoint setting of the action-specific Dockerfile.

**Comment by jetersen** [comment]
probot github adapter seems sufficient.
