### ISSUE TITLE
Action on push tag does not work after the release is published.

### ISSUE THREAD

**Issue by ElenaShlykova** [release-drafter/release-drafter#550]
Action on push tag does not work after the release is published.
I have an action to release a build on push tag action:
![image](https://user-images.githubusercontent.com/61818651/83443769-f4d38d80-a452-11ea-9df6-76b18c6b8d52.png)
And I also add the default release-drafter.yml file to prepare release draft. 
Everything works perfectly, except that when I publish this draft my build-installer action does not start. At the same time, I see that the tag has been added. Also, if I create a draft manually before combining the PR, everything works, and the build-installer action starts.
The only difference that I see is that when a draft was created with an action (release-drafter.yml), the user who releases the build is githubactions:
![image](https://user-images.githubusercontent.com/61818651/83444385-fbaed000-a453-11ea-91f3-7b6ad3aae51d.png)
Can this be fixed?

**Comment by jetersen** [comment]
See #546 😅

**Comment by jetersen** [comment]
There is no option to impersonate when creating a release, so if you want someone else to show as the releaser you have to use a different token.

**Comment by gvolpe** [comment]
Hi @jetersen ,

I've been trying to set up release drafter in some open-source projects and the draft releases are created without issues by `github-actions`. Now, when clicked on `Publish release`, a new tag along with the release notes were created: https://github.com/profunktor/fs2-rabbit/releases/tag/v3.0.0.

Unfortunately, the automated release workflow that should have been triggered by the newly created tag wasn't triggered.

I feel this issue is related but I fail to understand how I could use a different token when clicking on `Publish release`. Any chances you could expand on that? Or give me some pointers?

Much appreciated :pray:

**Comment by gvolpe** [comment]
Hmm it seems this is not supported by GH actions: https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250/33

**Comment by jetersen** [comment]
publish release does trigger release drafter becauase of it being a github action app atm see #549

**Comment by gvolpe** [comment]
I think I wasn't clear enough.

I have a [workflow](https://github.com/profunktor/fs2-rabbit/blob/master/.github/workflows/release.yml) that should be triggered when a new tag is created. However, after clicking on `Publish release` on the drafted release notes created by `github-actions` (using release drafter), this workflow is not triggered by the newly created tag.
