### ISSUE TITLE
does not work on any trigger other than push and pull_request

### ISSUE THREAD

**Issue by maximousblk** [release-drafter/release-drafter#595]
I was trying to set up a workflow using `workflow_dispatch` event so that I can manually trigger this action on demand and use certain inputs to specify tags and versions.

But this doesn't work because this action doesn't seem to work with this setup.

is there any other way I can trigger this on demand?

**Comment by jetersen** [comment]
https://github.blog/changelog/2020-05-26-github-actions-re-run-successful-jobs/ ? :)

**Comment by maximousblk** [comment]
Custom inputs on every run?

**Comment by jetersen** [comment]
Why does it have to be so complex, it goes beyond what release drafter was meant for... 😢

**Comment by maximousblk** [comment]
It's that would have been nice to have.

I have a very specific workflow which requires this kind of control but i guess not everyone needs that.

though I was wondering why is it it limited to only push type events?

**Comment by nebhale** [comment]
@jetersen Another reason for supporting `workflow_dispatch` is for a re-run when PR labels have changed.  For example, on the latest commit release drafter builds the list of changes and categorizes them in the changelog.  I notice that the categorization is wrong, and update a couple of PRs with new or different labels.  At this point, I _could_ re-run the action from the latest commit, but it's not conceptually accurate.  Supporting `workflow_dispatch` (for my needs, with no inputs) to trigger a refresh of the release notes is conceptually accurate because the change doesn't relate to the last commit, but rather all of the PRs that are part of the next release.

**Comment by maximousblk** [comment]
Any updates on this?

**Comment by jetersen** [comment]
This was fixed in #546
