### ISSUE TITLE
Stop creating new release note draft and update the existing draft instead

### ISSUE THREAD

**Issue by cliu123** [release-drafter/release-drafter#732]
If you look at the release note drafts here, you'll notice that upon a new PR gets merged, the release drafter generates a new release note draft with the info of the new PR, instead of updating the existing draft.
https://github.com/opendistro-for-elasticsearch/security/releases

However, keeping one release note draft updated is the expected behavior.

**Comment by jetersen** [comment]
Your running not standard release numbers most likely causing the issue.

**Comment by cliu123** [comment]
> Your running not standard release numbers most likely causing the issue.

The format of release number has to be consistent with the past releases. Is there a way to fix this without changing the format of release number?

**Comment by jetersen** [comment]
Currently we only support semver. So major, minor, patch. It would require some effort to support other formats.
Though we support omitting minor and patch.

I suggest to bump major version and drop the fourth digit to follow the semver standard.

**Comment by cathex-matt** [comment]
@jetersen So just adding a prefix 'v' break the standard behavior?

Because that's what I'm experiencing now. So I tried to deploy a first action with only the autolabeler enabled and then the one in charge of creating the draft on each PR getting merged, but there is no such way of disabling the draft creation in the configuration.

**Comment by crazy-matt** [comment]
@jetersen So just adding a prefix 'v' break the standard behavior?

Because that's what I'm experiencing now. So I tried to deploy a first action with only the autolabeler enabled and then the one in charge of creating the draft on each PR getting merged, but there is no such way of disabling the draft creation in the configuration.

**Comment by crazy-matt** [comment]
Is it possible to used the config file for 2 different actions release-drafter/release-drafter:
* one just autolabelling
* the second one creating the draft on PR closed and merged

How to disable the draft creation would be my question here.

**Comment by jetersen** [comment]
@crazy-matt you would use the `tag-template` to prefix the `v`

See
https://github.com/release-drafter/release-drafter/blob/0bc3bc59906b1dac1b608cc7ff5441fcb86ad6c9/.github/release-drafter.yml#L1-L2

Yes you can create multiple workflows and point to different config file names via action input, see docs.
