### ISSUE TITLE
Release notes for release branches

### ISSUE THREAD

**Issue by MelGrubb** [release-drafter/release-drafter#844]
Maybe I'm just doing something wrong, but how would I get release notes for a release or stabilization branch? We follow something more like GitHubFlow, and nothing will ever be deployed from "main". Our main branch is the eternal v.next development branch. When it comes time to release, we peel off a release/v1.2 (major.minor only) branch, and all the 1.2 stabilization work happens there (e.g. 1.2.3, 1.2.4, etc). It's these release branches that need the notes, because they're the branches that end up being deployed out to the world. I tried changing the trigger to "release/*", but it didn't kick in. What am I missing here?

**Comment by Skarlso** [comment]
https://github.com/release-drafter/release-drafter/issues/835

Sadly, you can't configure multiple branches if that's what you are looking for. The template file needs to be on the default branch.

**Comment by ssbarnea** [comment]
I do not need different configurations and I think that using the configuration from the main branch is ok. On the other on some projects I do have maintenance branches like `stable/` and what happened when I merged a backport to that was bit of a total mess:

* A new draft-release was created against `main` instead of `stable/3.4`
* The release number computed was wrong due to being based on `main`

I suspect that the second problem is just a side effect from the first but I am not aware of any method for preventing it and that can lead to really costly mistakes (releases).

Did anyone found a workaround or another similar tool that can deal with that?

**Comment by jetersen** [comment]
Should be possible to craft an action with filter-by-commitish and version input based on output from another action. Potentially you want to have multiple config files as well.

Though I would suggest git flow is not the best approach to releases and CI/CD:

> Gitflow is a legacy Git workflow that was originally a disruptive and novel strategy for managing Git branches.
> Gitflow has fallen in popularity in favor of [trunk-based workflows](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development), which are now considered best practices for modern continuous software development and [DevOps](https://www.atlassian.com/devops/what-is-devops) practices.
> Gitflow also can be challenging to use with [CI/CD](https://www.atlassian.com/continuous-delivery). This post details Gitflow for historical purposes.
> https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
