### ISSUE TITLE
support `pull_request_target` to enable the autolabler to work on forked PRs

### ISSUE THREAD

**Issue by ITProKyle** [release-drafter/release-drafter#868]
For open source projects, the most common way to contribute code is to fork the repo and PR from the fork. This results in the `secret.GITHUB_TOKEN` passed to this action for `pull_request` events to have read-only permissions preventing labels from being applied to the PR.

The [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) provides a safe alternative for triggering actions from PRs by running in the context of the base repo rather than the fork. This prevents potentially malicious code from being executed (unless the maintainers don't follow best practices when using this event type). It also provides a `secret.GITHUB_TOKEN` with write access to the base repo even for PRs from forks.

Currently when trying to use `pull_request_target` as a trigger for the action, it does not do anything.

**Comment by DVN237294** [comment]
Having this issue as well.
Bit of a shot in the dark, since I don't know much about release drafter (and actions in general), but I would think that it is just a matter of adding 
```
'pull_request_target.opened',
'pull_request_target.reopened',
'pull_request_target.synchronize'
```
to the list here:
https://github.com/release-drafter/release-drafter/blob/349214e6b3b889d8b333c012cc61a1f1753baf40/index.js#L25-L31

And passing the correct git ref to release drafter:
```
GITHUB_REF: ${{ github.event.pull_request.head.sha }}
```

Or is there more to it than that?
