### ISSUE TITLE
Minimal autolabeler example

### ISSUE THREAD

**Issue by dil-bnacey** [release-drafter/release-drafter#951]
Does anyone have a working minimal example of the autolabeler feature adding labels to PRs?

I've followed all documentation I can find. But, the autolabeler never seems to activate at all.

**Comment by dil-bnacey** [comment]
The issue I'm facing seems to be related to an "Internal" Organization repo.

Autolabeler is working as expected on both personal and organization "private" repos.

**Comment by dil-bnacey** [comment]
I have created a clean "internal" repo in my organization.

Autolabeler is working as expected in my clean repo.

I'll close this issue while I continue to investigate what is wrong with my original repo.

**Comment by jamesnswithers** [comment]
@bnacey did you find any more info on that issue? i am seeing a similar problem with an internal repo in our Org.

**Comment by bnacey** [comment]
@jamesnswithers What I found was that everything works as expected only after all configs have need merged to your "main" branch.

Changing the labeling configs on a PR will not effect that PR itself since the Action only looks at "main". This made things difficult to test initially, but really isn't too bad once you get it working the way you want.

**Comment by jamesnswithers** [comment]
got it, thanks a lot @bnacey
