### ISSUE TITLE
Is this action still under active development?

### ISSUE THREAD

**Issue by lucacome** [release-drafter/release-drafter#958]
First of all thanks for all the work that you do.

But as the title says, is this still active? There are 108 issues and 28 PRs open and the last release was in March. It seems to me that it's not very active. 😞 

Not trying to be negative or anything, I like this project, but I'm just wondering if I need to start looking for an alternative.

Cheers.

**Comment by vlsi** [comment]
Just for reference, here's GitHub doc: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by jetersen** [comment]
Active development properly not, unless someone is willing to contribute new features. I myself don't have a need for more features. 
The project is definitely still maintained and if anyone is willing to contribute, I am happy to review.

Just because last release was March, does not mean the project is dead, there simply were no real reason to push a new release as it was working for the most parts.

**Comment by jetersen** [comment]
I have tried to make it easier to release and maintain the project:

Seems like the project is "really" active although somewhat one sided on my part 😅 

![image](https://user-images.githubusercontent.com/1661688/150233632-5487e4d2-0ca6-4811-aad6-a535c10c1576.png)
